### ISSUE TITLE
Issue on start

### ISSUE THREAD

**Issue by llogan382** [brxck/gatsby-starter-stripe#17]
When running "gatsby develop" on initial load, an error occurred. 

## Expected Behavior

When running gatsby develop, a local dev environment should be launched

## Current Behavior

This is the error in red in the terminal:
  Error: [ { GraphQLError: Cannot query field "allStripeSku" on type "Query". Di  d you mean "allSite"?
Complete terminal response below. 

## Steps to Reproduce (for bugs)

1. install theme using "gatsby new example-site-for-square-starter https://github.com/jonniebigodes/example-site-for-square-starter"
2. "cd gatsby starter-stripe"
3. "gatsby develop"
4.

## Your Environment

* Version used:
Node v. 10.15.3

* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
Mac OS High Sierra
* Link to your project:

UNHANDLED REJECTION [ { GraphQLError: Cannot query field "allStripeSku" on type "Query". Did you mean "allSite"?
      at Object.Field (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)
      at Object.enter (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/graphql/language/visitor.js:324:29)
      at Object.enter (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/graphql/language/visitor.js:375:25)
      at visit (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/graphql/language/visitor.js:242:26)
      at validate (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/graphql/validation/validate.js:73:24)
      at graphqlImpl (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/graphql/graphql.js:99:49)
      at /Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/graphql/graphql.js:28:59
      at new Promise (<anonymous>)
      at graphql (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/graphql/graphql.js:26:10)
      at GraphQLRunner.query (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/dist/query/graphql-runner.js:38:12)
      at /Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/dist/bootstrap/graphql-runner.js:11:37
      at Object.exports.createPages (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/gatsby-node.js:21:10)
      at runAPI (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/dist/utils/api-runner-node.js:234:37)
      at resolve (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/dist/utils/api-runner-node.js:347:15)
      at Promise._execute (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/debuggability.js:313:9)
      at Promise._resolveFromExecutor (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:488:18)
      at new Promise (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:79:10)
      at Promise.mapSeries.plugin (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/dist/utils/api-runner-node.js:346:12)
      at tryCatcher (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/reduce.js:155:18)
      at Object.gotAccum (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/reduce.js:144:25)
      at Object.tryCatcher (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromiseCtx (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:611:10)
      at _drainQueueStep (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/async.js:142:12)
      at _drainQueue (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues (/Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/node_modules/gatsby/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
    message:
     'Cannot query field "allStripeSku" on type "Query". Did you mean "allSite"?',
    locations: [ [Object] ] } ]

  Error: [ { GraphQLError: Cannot query field "allStripeSku" on type "Query". Di  d you mean "allSite"?

  - new Promise

  - graphql-runner.js:38 GraphQLRunner.query
    [gatsby-starter-stripe]/[gatsby]/dist/query/graphql-runner.js:38:12

  - graphql-runner.js:11
    [gatsby-starter-stripe]/[gatsby]/dist/bootstrap/graphql-runner.js:11:37

  - gatsby-node.js:21 Object.exports.createPages
    /Users/llogan/Local Sites/gatsby-stripe/gatsby-starter-stripe/gatsby-node.js    :21:10

  - api-runner-node.js:234 runAPI
    [gatsby-starter-stripe]/[gatsby]/dist/utils/api-runner-node.js:234:37

  - api-runner-node.js:347 resolve
    [gatsby-starter-stripe]/[gatsby]/dist/utils/api-runner-node.js:347:15

  - debuggability.js:313 Promise._execute
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/debuggability.js:313:    9

  - promise.js:488 Promise._resolveFromExecutor
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/promise.js:488:18

  - promise.js:79 new Promise
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/promise.js:79:10

  - api-runner-node.js:346 Promise.mapSeries.plugin
    [gatsby-starter-stripe]/[gatsby]/dist/utils/api-runner-node.js:346:12

  - util.js:16 tryCatcher
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/util.js:16:23

  - reduce.js:155 Object.gotValue
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/reduce.js:155:18

  - reduce.js:144 Object.gotAccum
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/reduce.js:144:25

  - util.js:16 Object.tryCatcher
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/util.js:16:23

  - promise.js:517 Promise._settlePromiseFromHandler
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/promise.js:517:31

  - promise.js:574 Promise._settlePromise
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/promise.js:574:18

  - promise.js:611 Promise._settlePromiseCtx
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/promise.js:611:10

  - async.js:142 _drainQueueStep
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/async.js:142:12

  - async.js:131 _drainQueue
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues
    [gatsby-starter-stripe]/[gatsby]/[bluebird]/js/release/async.js:17:14

  - message:

  - 'Cannot query field "allStripeSku" on type "Query". Did you mean "allSite"?'    ,

  - locations: [ [Object] ] } ]

  - index.js:133 process.on.reason
    [lib]/[gatsby-cli]/lib/index.js:133:14

  - index.js:155 processEmit
    [lib]/[gatsby-cli]/[signal-exit]/index.js:155:32

  - index.js:155 processEmit [as emit]
    [gatsby-starter-stripe]/[signal-exit]/index.js:155:32

  - promises.js:119 emitPromiseRejectionWarnings
    internal/process/promises.js:119:20

  - next_tick.js:69 process._tickCallback
    internal/process/next_tick.js:69:34

**Comment by gixxerblade** [comment]
Start it by running `npm run start`

**Comment by brxck** [comment]
The above is correct. The serverless functions must also be running, see `4. Start development servers` of the [README](https://github.com/brxck/gatsby-starter-stripe#getting-started).
