### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yansusanto** [brxck/gatsby-starter-stripe#32]
Hi there,

I hope someone in the know could help point me in the right direction. What could I possibly be missing? Thank you!

```
/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at startDevelopProxy (/Users/adam/PROJECT/MAIONE/node_modules/gatsby/src/utils/develop-proxy.ts:86:10)
    at module.exports (/Users/adam/PROJECT/MAIONE/node_modules/gatsby/src/commands/develop.ts:124:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by yansusanto** [comment]
Oh apparently, we can't run another app at the same port :8000 (even though I have none running)

**Comment by yansusanto** [comment]
Been trying for hours, just couldn't get pass

`Cannot query field "quantity" on type "StripeSkuInventory".`

I've created a test data on Stripe and follow everything to a "T"

**How do we exactly add "quantity" to Product on Stripe?** 

Hopefully someone is kind enough to point me in the right direction. What supposedly a 5-min installation turned in hours *scratching my head*

Thanks everyone.

**Comment by thomasvaeth** [comment]
@yansusanto Did you figure this out? You have to use the Stripe API to add SKU/quantity.

**Comment by brxck** [comment]
The latest version of the starter comes with Stripe fixtures, which I hope will alleviate problems others are having with getting the proper data setup in Stripe. It also moves from the Orders API (Skus) to the Prices API. 

Please let me know if you have any problems with the new version of the starter!
