### ISSUE TITLE
Issue with Stripe Redirect to Checkout

### ISSUE THREAD

**Issue by VinceGrilli** [brxck/gatsby-starter-stripe#37]
Everything works great when run on a local server but once deployed to Netlify and I click the checkout button I'm getting this error:

stripe.redirectToCheckout: You must provide one of lineItems, items, or sessionId.

It works locally, I can click checkout and it redirects me to Stripe's checkout page with the session id in the URL. Once I pay it redirects me to the success page I set up also with the session id passed in the URL. But once deployed to Netlify it doesn't seem to be able to get the session id. This is the output in the Netlify function log:

{"errorType":"Error","errorMessage":"Not a valid URL","code":"url_invalid","type":"StripeInvalidRequestError","raw":{"code":"url_invalid","doc_url":"https://stripe.com/docs/error-codes/url-invalid","message":"Not a valid URL","param":"success_url","type":"invalid_request_error","headers":{"server":"nginx","date":"Tue, 01 Mar 2022 13:04:22 GMT","content-type":"application/json","content-length":"212","connection":"keep-alive","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, HEAD, OPTIONS, DELETE","access-control-allow-origin":"*","access-control-expose-headers":"Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required","access-control-max-age":"300","cache-control":"no-cache, no-store","idempotency-key":"4c9bf0e5-dd71-4c2c-bbee-d1591e16810f","original-request":"req_95CZXPLJLfLjCM","request-id":"req_95CZXPLJLfLjCM","stripe-version":"2020-08-27","strict-transport-security":"max-age=31556926; includeSubDomains; preload"},"statusCode":400,"requestId":"req_95CZXPLJLfLjCM"},"rawType":"invalid_request_error","doc_url":"https://stripe.com/docs/error-codes/url-invalid","param":"success_url","headers":{"server":"nginx","date":"Tue, 01 Mar 2022 13:04:22 GMT","content-type":"application/json","content-length":"212","connection":"keep-alive","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, HEAD, OPTIONS, DELETE","access-control-allow-origin":"*","access-control-expose-headers":"Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required","access-control-max-age":"300","cache-control":"no-cache, no-store","idempotency-key":"4c9bf0e5-dd71-4c2c-bbee-d1591e16810f","original-request":"req_95CZXPLJLfLjCM","request-id":"req_95CZXPLJLfLjCM","stripe-version":"2020-08-27","strict-transport-security":"max-age=31556926; includeSubDomains; preload"},"requestId":"req_95CZXPLJLfLjCM","statusCode":400,"stack":["Error: Not a valid URL","    at Function.generate (/var/task/node_modules/stripe/lib/Error.js:40:16)","    at IncomingMessage.<anonymous> (/var/task/node_modules/stripe/lib/StripeResource.js:180:33)","    at Object.onceWrapper (events.js:519:28)","    at IncomingMessage.emit (events.js:412:35)","    at endReadableNT (internal/streams/readable.js:1334:12)","    at processTicksAndRejections (internal/process/task_queues.js:82:21)"]}

I haven't touched the code in Checkout or orderCreate, so I'm not sure if this is a problem with Stripe or Netlify. Any help here would be greatly appreciated. I've been trying to figure this out on my own for a few days now

**Comment by VinceGrilli** [comment]
Problem solved. I was using quotes in my environmental variables. Apparently Netlify doesn't like that
